spring.application.name=SmartVolt

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartvolt}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dev}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# MQTT Broker
mqtt.broker.url=ssl://smartvolt.drewmeyers.com:8883
mqtt.client.id=smartvolt-server
mqtt.username=${MQTT_USERNAME}
mqtt.password=${MQTT_PASSWORD}

# TLS - path to public cert
mqtt.tls.ca-cert-path=/etc/letsencrypt/live/smartvolt.drewmeyers.com/chain.pem

# Topic config - Tasmota style
mqtt.topic.telemetry=smartvolt/devices/+/tele/SENSOR
mqtt.topic.lwt=smartvolt/devices/+/tele/LWT
mqtt.topic.command-prefix=smartvolt/devices/

# HTTPS for Spring Boot
server.port=443
server.ssl.enabled=true
server.ssl.certificate=/etc/letsencrypt/live/smartvolt.drewmeyers.com/fullchain.pem
server.ssl.certificate-private-key=/etc/letsencrypt/live/smartvolt.drewmeyers.com/privkey.pem

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Init for my sonoff
smartvolt.device.id=sonoff-01
smartvolt.api.key=${SMARTVOLT_API_KEY}
