spring.application.name=smartvolt

# Database
spring.datasource.url=${jdbc:postgresql://localhost:5432/smartvolt}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dev}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# MQQT Broker
mqtt.broker.url=${MQQT_BROKER_URL}
mqtt.client.id=smartvolt-server
mqqt.username=${MQQT_USERNAME}
mqtt.password=${MQQT_PASSWORD}

# Topics
mqqt.topic.telemetry=smartvolt/devices/+/telemetry
mqtt.topic.command=smartvolt/devices/{deviceId}/command
mqqt.topic.status=smartvolt/devices/+/status

# Init for my sonoff
smartvolt.device.id=sonoff=01 
smartvolt.api.key=${SMARTVOLT_API_KEY}
