name: SmartVolt Edge CI

on:
  push:
    branches: [ main ]
    paths:
      - 'shared/**'
      - 'edge/**'
      - 'pom.xml'
  pull_request:
    branches: [ main ]
    paths:
      - 'shared/**'
      - 'edge/**'
      - 'pom.xml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
        CLOUD_API_KEY: ci-test-key

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build and Test (shared + edge)
      run: |
        chmod +x mvnw
        ./mvnw verify -B -pl shared,edge -am
